### PR TITLE
update at force reinstall

### PR DESCRIPTION
**Pull request by rbaumgar**
## Checklist/ToDo's

- [x] Added documentation?
- [ ] Added release note entry? (  docs/release-notes.md )
- [x] Tested?

### CODE REVIEW

**Comment by rbaumgar** [comment]
update at force reinstall documentation

**Comment by rbo** [comment]
The OC command is create. You can also use:

```bash
$ openshift-install coreos print-stream-json | jq '.architectures.x86_64.artifacts.qemu.formats."qcow2.gz".disk.location'
"https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.14-9.2/builds/414.92.202310210434-0/x86_64/rhcos-414.92.202310210434-0-qemu.x86_64.qcow2.gz"
```

Or just download at: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.15/4.15.0/rhcos-4.15.0-x86_64-qemu.x86_64.qcow2.gz

**Comment by rbaumgar** [comment]
The command I found is the command fitting to your running cluster...

**Comment by rbo** [comment]
Agree, is very nice. I would like to document all three ways...

**Comment by rbaumgar** [comment]
what is the tired way?

**Comment by rbo** [comment]
Fixed & merged...

**Pull request merged**
