### PR TITLE
Issue80

### LINKED ISSUE #80: Add a option to disable letsencrypt

### PR DESCRIPTION
**Pull request by tahonen**
Fixes #80 option to skip Let's encrypts certs

### CODE REVIEW

**Comment by rbo** [comment]
What is with: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/467cc3de315b58b0ed05e216931b94d988a47275/ansible/renewal-certificate.yml#L10 to skip certificate-install.yml ? In case you run `ansible/renewal-certificate.yml` with `letsencrypt_disabled=true`

**Comment by tahonen** [comment]
Was thinkng about that, but you dont run that playbook if you dont have certs. Might be good to add to prevent red text

**Comment by rbo** [comment]
Switch base to devel

**Comment by rbo** [comment]
Rebase branch to devel and cleanup. (squash commits)

**Comment by rbo** [comment]
- Added documentation and update release-note.
- Added letsencrypt_disabled support to ansible/renewal-certificate.yml

**Pull request merged**
