### PR TITLE
OKD Implementation

### PR DESCRIPTION
**Pull request by sandrich**
## Description
This is work in progress to look into #136 
I don't have a test system that allows me going past the download artifacts.

There is a sample-cluster-okd.yml file with the specific settings that are required.

## Checklist/ToDo's

- [X] Added documentation?
- [x] Tested?
- [x] OKD artifacts download works
- [x] Refactored

### CODE REVIEW

**Comment by sandrich** [comment]
@rbo @Alexr03 do you have a system to test?

**Comment by Alexr03** [comment]
I have a system to test against, i'll give it a shot now

**Comment by Alexr03** [comment]
Initial tests I seem to be getting a failures at:

image
I believe the condition is incorrect and instead should be: `install_okd is not defined`

----

image
The fcos image is downloaded as a .gz not .xz, the `download coreos` task is setting the destination file name extension to .gz

**Comment by sandrich** [comment]
> I am testing against CentOS 8.
> 
> Initial tests I seem to be getting a failures at:
> 
> 
> 
> image
> 
> I believe the condition is incorrect and instead should be: `install_okd is not defined`
> 
> 
> 
> ----
> 
> 
> 
> image
> 
> The fcos image is downloaded as a .gz not .xz, the `download coreos` task is setting the destination file name extension to .gz
> 
> 
> 
> ----
> 
> 
> 
> image
> 
> Cannot seem to SSH/ping into any of the vm's - Running `systemctl restart NetworkManager.service` will fix this.

Did you set all the variables in the okd sample file?

**Comment by Alexr03** [comment]
Yes - This was the cluster.yml I used https://pastebin.com/dLjwGLgJ

**Comment by sandrich** [comment]
"Unzip coreos" should be skipped and "unxz coreos" should be called instead.

Will fix that. What other issues did you spot? Did it download FCOS image and properly load it in libvirt? Did you check the virsh console? Also can you check the dhcp leases?

**Comment by sandrich** [comment]
@Alexr03 pushed a new update that should fix the ".gz"

**Comment by Alexr03** [comment]
Turns out the connectivity is fine, it was just taking a while on these stages 
image

It took about 10 minutes to for this to complete. As it is now running the bootstrap. 
Not sure if this is normal for how long it normally takes.

**Comment by sandrich** [comment]
@Alexr03 are you on SSD?

**Comment by Alexr03** [comment]
@sandrich I am

**Comment by sandrich** [comment]
@Alexr03 not sure how long it took on my end. Let's see if you can ssh to bootstrap and if the cluster is forming.

**Comment by Alexr03** [comment]
Can confirm I can ssh into bootstrap and its forming the cluster.

**Comment by sandrich** [comment]
@Alexr03 ideally you destroy and recreate from scratch with my updated code once the cluster is up and running. Just so I can test it end-to-end

**Comment by Alexr03** [comment]
I let the bootstrap run through anyway and when it reached registry it failed due to SSL.
image

I will destroy and recreate the cluster now to test e2e.

**Comment by Alexr03** [comment]
Same error after destroying and recreating unfortunately.

**Comment by sandrich** [comment]
> Same error after destroying and recreating unfortunately.

Dns error or extraction error?

**Comment by Alexr03** [comment]
The ssl error for accessing the cluster api. - https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/pull/137#issuecomment-716733858
Maybe linked to #117 ?

**Comment by sandrich** [comment]
Not sure this is related to OKD @rbo ?

**Comment by Alexr03** [comment]
Managed to get it all up and running after trial and error alot of times. Not sure what was causing it, will do a little bit more investigating into it.

I let the cluster settle and it seems that everything is working as expected apart from the community-operators pod in openshift-marketplace. Seems to be getting `CrashLoopBackOff` error. I think I remember seeing this when I installed ocp4. I don't think its down to okd. 
Checking out the logs, I don't see any obvious reasons why its crashing 🙃

**Comment by sandrich** [comment]
@rbo PR is ready for review

**Comment by Alexr03** [comment]
24 hours later --
Restarted the cluster and it seems the apiserver will not come back up, presumably due to a invalid certificate on the api.cluster.domain.tld

I am getting EOF errors when attempting to login, 

```
[root@static hetzner-ocp4]# unset KUBECONFIG
[root@static hetzner-ocp4]# oc login -u Alex
Server [https://localhost:8443]: https://x.y.z.a:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Unable to connect to the server: EOF
```
I am able to see the cluster is up via looking at the `<cluster ip>:6443/version`
image

**Comment by rbo** [comment]
just for information: it will take some time to review this.

**Comment by rbo** [comment]
Everything is merged into okd4 branch for further tests.

**Pull request merged**
