### PR TITLE
Add Gandi DNS provider

### PR DESCRIPTION
**Pull request by debovema**
## Checklist/ToDo's

- [x] Added documentation? Yes, the same as for other providers
- [x] Added release note entry? (  docs/release-notes.md )
- [x] Tested?

### CODE REVIEW

**Comment by rbo** [comment]
@debovema Can you be so kind and update to the latest devel tree version?

**Comment by debovema** [comment]
> @debovema Can you be so kind and update (rebase) to the latest devel tree version?

Done

**Comment by rbo** [comment]
/test

@debovema Mh I have to improve the /test /retest is allowed as long as an Owner / Me approved it ones.

**Pull request merged**
