### PR TITLE
Fix/qemu

### PR DESCRIPTION
**Pull request by marcoklaassen**
## Description
Fixes qemu-img: Deprecate use of -b without -F. 
Without this fix task `Create disk for {{ vm_instance_name }}` fails with a message like 

```qemu-img: /var/lib/libvirt/images/[...]: Backing file specified without backing format\nDetected format of qcow2.```

## Checklist/ToDo's

- [ ] Added documentation?
- [ ] Added release note entry? (  docs/release-notes.md )
- [ ] Tested?

### CODE REVIEW

**Comment by rbo** [comment]
This is fixed in devel tree, I forgot to merge this into MAster :-(

**Comment by rbo** [comment]
eh nope it isn't mh ...

**Comment by rbo** [comment]
No it is: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/commit/783ad9071b348576068649608d9ef2841ceb1f16 - I'm confused

**Comment by marcoklaassen** [comment]
oh .. yes .. it should be fixed with https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/commit/783ad9071b348576068649608d9ef2841ceb1f16

**Comment by marcoklaassen** [comment]
sorry for the confusion :-D

**Comment by marcoklaassen** [comment]
next time i will pull the devel branch first ;-)

**Comment by rbo** [comment]
So we can close this PR?

**Pull request closed without merging**
