### PR TITLE
Update vm.xml.j2

### PR DESCRIPTION
**Pull request by lucamaf**
enable cpu features to support new version of ironic metal operator version

## Checklist/ToDo's

- [ ] Added documentation?
- [ ] Added release note entry? (  docs/release-notes.md )
- [ ] Tested?

### CODE REVIEW

**Review by rbo — CHANGES_REQUESTED** [review]
Hi @lucamaf  thanks for the PR.

Your change would break the usage of `vm_special_cpu` configuration option.

https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/pull/250/files#diff-b8ed737b75e862e26363b880af6c22fdeed348824085e042f595499450eb3359R13-R15

Does the cpu features works on AMD cpu too? 

In case you just need this feaure for special purpose you can add this t your cluster.yaml

```yaml

vm_special_cpu: |
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>qemu64</model>
    <feature policy='require' name='avx'/>
    <feature policy='require' name='avx2'/>
    <feature policy='require' name='lm'/>
    <feature policy='require' name='cmov'/>
    <feature policy='require' name='cx8'/>
    <feature policy='require' name='fpu'/>
    <feature policy='require' name='fxsr'/>
    <feature policy='require' name='mmx'/>
    <feature policy='require' name='syscall'/>
    <feature policy='require' name='sse2'/>
    <feature policy='require' name='cx16'/>
    <feature policy='require' name='popcnt'/>
    <feature policy='require' name='sse4.1'/>
    <feature policy='require' name='sse4.2'/>
    <feature policy='require' name='ssse3'/>
    <feature policy='require' name='x2apic'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='lahf_lm'/>
    <feature policy='disable' name='svm'/>
  </cpu>
```

Please rebase/update your branch to devel tree. 

Thanks
Robert

**Comment by lucamaf** [comment]
got it, can close it
the approach I'm taking right now is to edit the generated xml config of the vm

**Comment by rbo** [comment]
@lucamaf just for information, I changed the default to `<cpu mode='host-passthrough'></cpu>` with #253 it's already in the devel branch and will be merged into master soon.

**Pull request closed without merging**
