### PR TITLE
Add Rocky Linux 9 support

### PR DESCRIPTION
**Pull request by debovema**
## Checklist/ToDo's

- [x] Added documentation? N/A, behaviour not changed
- [x] Added release note entry? (  docs/release-notes.md )
- [x] Tested? Yes, on a Scaleway bare metal server

### CODE REVIEW

**Comment by rbo** [comment]
How do you instal Rocky 9?  Looks like basis image is not available from hetzner:
```bash
root@rescue ~ # ls -1 images/{CentOS,Rocky}*
images/CentOS-79-64-minimal.tar.gz
images/CentOS-79-64-minimal.tar.gz.sig
images/CentOS-80-stream-amd64-base.tar.gz
images/CentOS-80-stream-amd64-base.tar.gz.sig
images/CentOS-85-64-minimal.tar.gz
images/CentOS-85-64-minimal.tar.gz.sig
images/Rocky-85-amd64-base.tar.gz
images/Rocky-85-amd64-base.tar.gz.sig
```

**Comment by debovema** [comment]
I used this repository to create an OCP cluster on an already provisioned bare metal server running Rocky 9 (on Scaleway btw, not Hetzner).
Maybe this repository should be renamed libvirt-ocp4 and leave the [00-provision-hetzner.yml](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/devel/ansible/00-provision-hetzner.yml) playbook optional ?

**Comment by rbo** [comment]
Good point, I have already thought about renaming it, but I am not clear about the impact.

**Comment by rbo** [comment]
@debovema  Let's move the renaming discussion into an own Issue #232

**Comment by rbo** [comment]
@debovema Can you be so kind and update (rebase) to the latest devel tree version?

**Comment by debovema** [comment]
> @debovema Can you be so kind and update (rebase) to the latest devel tree version?

Done

**Pull request merged**
