### PR TITLE
added jq to download packages, updated air-gapped installation doc

### PR DESCRIPTION
**Pull request by tjungbauer**
## Checklist/ToDo's

- [x ] Added documentation?
- [ ] Added release note entry? (  docs/release-notes.md )
- [ x] Tested?

### CODE REVIEW

**Comment by tjungbauer** [comment]
Hey, 

I have added jq-package into the ansible task since it it widly used and required for ait-gapped environment setup :) 

I also updated the air-gapped documentation and added more details and the usage of the oc-mirror plugin

**Comment by rbo** [comment]
@tjungbauer thanks for contribution. I rebase your master branch to devel tree. Just for information.

**Pull request merged**
